name: Cleanup

on: workflow_dispatch

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  cleanup-images:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/delete-package-versions@v4
      with: 
          package-name: goucrt
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'

